import axios from 'axios';
import logger from '@kodingcaravan/shared/config/logger';

type Msg91Result =
  | { success: true; provider: 'msg91'; requestId?: string }
  | { success: true; provider: 'local' }
  | { success: false; provider: 'local'; error: string };

type Msg91VerifyResult =
  | { success: true; provider: 'msg91' }
  | { success: true; provider: 'local' }
  | { success: false; provider: 'local'; error: string };

type Msg91RetryResult =
  | { success: true; provider: 'msg91' }
  | { success: true; provider: 'local' }
  | { success: false; provider: 'local'; error: string };

/**
 * Send OTP using MSG91 - OTP is generated by MSG91
 */
export async function sendMsg91Otp(phone: string): Promise<Msg91Result> {
  const authKey = process.env.MSG91_AUTH_KEY;
  const templateId = process.env.MSG91_TEMPLATE_ID;
  const isDev = process.env.NODE_ENV !== 'production';

  const cleaned = phone.replace(/\D/g, '');
  const normalizedPhone = cleaned.startsWith('91')
    ? cleaned
    : `91${cleaned}`;

  if (!authKey || !templateId) {
    if (isDev) {
      logger.debug('OTP will be generated by MSG91 (dev mode)', {
        phone: normalizedPhone.substring(0, 4) + '****',
        service: 'trainer-auth-service',
      });
      return { success: true, provider: 'local' };
    }
    return { success: false, provider: 'local', error: 'MSG91 config missing' };
  }

  try {
    const otpExpiry = process.env.MSG91_OTP_EXPIRY || '5';
    const otpLength = process.env.MSG91_OTP_LENGTH || '6';
    const realTimeResponse = process.env.MSG91_REALTIME_RESPONSE || '1';

    const params = new URLSearchParams({
      mobile: normalizedPhone,
      authkey: authKey,
      otp_expiry: otpExpiry,
      otp_length: otpLength,
      template_id: templateId,
      realTimeResponse: realTimeResponse,
    });

    logger.debug('Sending OTP request via MSG91', {
      phone: normalizedPhone.substring(0, 4) + '****',
      templateId,
      otpExpiry,
      otpLength,
      service: 'trainer-auth-service',
    });

    const response = await axios.post(
      `https://control.msg91.com/api/v5/otp?${params.toString()}`,
      {},
      {
        headers: {
          'Content-Type': 'application/json',
        },
        timeout: 10000,
      }
    );

    const requestId = response.data?.request_id || 'N/A';
    logger.debug('MSG91 OTP response', {
      requestId,
      type: response.data?.type || 'N/A',
      phone: normalizedPhone.substring(0, 4) + '****',
      service: 'trainer-auth-service',
    });

    if (response.data?.type !== 'success') {
      throw new Error(`MSG91 API returned non-success: ${JSON.stringify(response.data)}`);
    }

    return { success: true, provider: 'msg91', requestId };
  } catch (err: any) {
    const errorData = err?.response?.data || err?.message;
    const errorMessage = typeof errorData === 'string' 
      ? errorData 
      : JSON.stringify(errorData);

    logger.error('MSG91 OTP send failed', {
      error: errorMessage,
      status: err?.response?.status,
      statusText: err?.response?.statusText,
      phone: normalizedPhone.substring(0, 4) + '****',
      service: 'trainer-auth-service',
    });

    if (isDev) {
      logger.debug('OTP generation skipped in dev mode (fallback)', {
        phone: normalizedPhone.substring(0, 4) + '****',
        service: 'trainer-auth-service',
      });
      return { success: true, provider: 'local' };
    }

    return {
      success: false,
      provider: 'local',
      error: `OTP delivery failed: ${errorMessage}`,
    };
  }
}

/**
 * Verify OTP using MSG91 verify endpoint
 */
export async function verifyMsg91Otp(
  phone: string,
  otp: string
): Promise<Msg91VerifyResult> {
  const authKey = process.env.MSG91_AUTH_KEY;
  const isDev = process.env.NODE_ENV !== 'production';

  const cleaned = phone.replace(/\D/g, '');
  const normalizedPhone = cleaned.startsWith('91')
    ? cleaned
    : `91${cleaned}`;

  if (!authKey) {
    if (isDev) {
      logger.debug('OTP verify skipped in dev mode', {
        phone: normalizedPhone.substring(0, 4) + '****',
        service: 'trainer-auth-service',
      });
      return { success: true, provider: 'local' };
    }
    return { success: false, provider: 'local', error: 'MSG91 config missing' };
  }

  try {
    const params = new URLSearchParams({
      mobile: normalizedPhone,
      otp: otp,
      authkey: authKey,
    });

    logger.debug('Verifying OTP via MSG91', {
      phone: normalizedPhone.substring(0, 4) + '****',
      service: 'trainer-auth-service',
    });

    const response = await axios.get(
      `https://control.msg91.com/api/v5/otp/verify?${params.toString()}`,
      {
        headers: {
          'Content-Type': 'application/json',
        },
        timeout: 10000,
      }
    );

    logger.debug('MSG91 OTP verify response', {
      type: response.data?.type || 'N/A',
      phone: normalizedPhone.substring(0, 4) + '****',
      service: 'trainer-auth-service',
    });

    if (response.data?.type !== 'success') {
      return {
        success: false,
        provider: 'local',
        error: response.data?.message || 'OTP verification failed',
      };
    }

    return { success: true, provider: 'msg91' };
  } catch (err: any) {
    const errorData = err?.response?.data || err?.message;
    const errorMessage = typeof errorData === 'string' 
      ? errorData 
      : JSON.stringify(errorData);

    logger.error('MSG91 OTP verify failed', {
      error: errorMessage,
      status: err?.response?.status,
      statusText: err?.response?.statusText,
      phone: normalizedPhone.substring(0, 4) + '****',
      service: 'trainer-auth-service',
    });

    if (isDev) {
      logger.debug('OTP verify accepted in dev mode (fallback)', {
        phone: normalizedPhone.substring(0, 4) + '****',
        service: 'trainer-auth-service',
      });
      return { success: true, provider: 'local' };
    }

    return {
      success: false,
      provider: 'local',
      error: `OTP verification failed: ${errorMessage}`,
    };
  }
}

/**
 * Retry/resend OTP using MSG91 retry endpoint
 */
export async function retryMsg91Otp(
  phone: string,
  retryType: 'text' | 'voice' = 'text'
): Promise<Msg91RetryResult> {
  const authKey = process.env.MSG91_AUTH_KEY;
  const isDev = process.env.NODE_ENV !== 'production';

  const cleaned = phone.replace(/\D/g, '');
  const normalizedPhone = cleaned.startsWith('91')
    ? cleaned
    : `91${cleaned}`;

  if (!authKey) {
    if (isDev) {
      logger.debug('OTP retry skipped in dev mode', {
        phone: normalizedPhone.substring(0, 4) + '****',
        retryType,
        service: 'trainer-auth-service',
      });
      return { success: true, provider: 'local' };
    }
    return { success: false, provider: 'local', error: 'MSG91 config missing' };
  }

  try {
    const params = new URLSearchParams({
      mobile: normalizedPhone,
      authkey: authKey,
      retrytype: retryType,
    });

    logger.debug('Retrying OTP via MSG91', {
      phone: normalizedPhone.substring(0, 4) + '****',
      retryType,
      service: 'trainer-auth-service',
    });

    const response = await axios.get(
      `https://control.msg91.com/api/v5/otp/retry?${params.toString()}`,
      {
        headers: {
          'Content-Type': 'application/json',
        },
        timeout: 10000,
      }
    );

    logger.debug('MSG91 OTP retry response', {
      type: response.data?.type || 'N/A',
      phone: normalizedPhone.substring(0, 4) + '****',
      retryType,
      service: 'trainer-auth-service',
    });

    if (response.data?.type !== 'success') {
      return {
        success: false,
        provider: 'local',
        error: response.data?.message || 'OTP retry failed',
      };
    }

    return { success: true, provider: 'msg91' };
  } catch (err: any) {
    const errorData = err?.response?.data || err?.message;
    const errorMessage = typeof errorData === 'string' 
      ? errorData 
      : JSON.stringify(errorData);

    logger.error('MSG91 OTP retry failed', {
      error: errorMessage,
      status: err?.response?.status,
      statusText: err?.response?.statusText,
      phone: normalizedPhone.substring(0, 4) + '****',
      retryType,
      service: 'trainer-auth-service',
    });

    if (isDev) {
      logger.debug('OTP retry accepted in dev mode (fallback)', {
        phone: normalizedPhone.substring(0, 4) + '****',
        retryType,
        service: 'trainer-auth-service',
      });
      return { success: true, provider: 'local' };
    }

    return {
      success: false,
      provider: 'local',
      error: `OTP retry failed: ${errorMessage}`,
    };
  }
}
